# Generated by Django 5.2.5 on 2025-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examaccesstoken',
            name='token',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
